# Weather prediction
- platform: yr
  name: YRWeather
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    - dewpointTemperature

# Moon phases
- platform: moon

- platform: systemmonitor
  resources:
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: last_boot
    - type: disk_use
      arg: "/"
    - type: disk_free
      arg: "/"

- platform: zestimate
  api_key: !secret zillowapi
  zpid:
    - !secret zillowpid

- platform: rest
  resource: https://api.ipify.org?format=json
  name: External IP
  value_template: '{{ value_json.ip }}'
  scan_interval: 10

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'time_utc'

# SNSMP SENSORS ################################################################
# Router uptime minutes
- platform: snmp
  name: router_uptime_minutes
  host: 192.168.1.1
  community: home
  scan_interval: 60
  baseoid: 1.3.6.1.2.1.25.1.1.0
  value_template: "{{ (value | int) // 6000 }}"
  unit_of_measurement: minutes

- platform: snmp
  name: router_cpu_load_1
  host: 192.168.1.1
  community: home
  scan_interval: 60
  baseoid: 1.3.6.1.4.1.2021.10.1.3.1
  value_template: "{{ (value | float) }}"
  unit_of_measurement: "load"

- platform: snmp
  name: router_cpu_load_5
  host: 192.168.1.1
  community: home
  scan_interval: 60
  baseoid: 1.3.6.1.4.1.2021.10.1.3.2
  value_template: "{{ (value | float) }}"
  unit_of_measurement: "load"

- platform: snmp
  name: router_cpu_load_15
  host: 192.168.1.1
  community: home
  scan_interval: 60
  baseoid: 1.3.6.1.4.1.2021.10.1.3.3
  value_template: "{{ (value | float) }}"
  unit_of_measurement: "load"

- platform: snmp
  name: if_counter_eth0_in
  host: 192.168.1.1
  community: home
  scan_interval: 60
  baseoid: 1.3.6.1.2.1.2.2.1.10.4
  value_template: "{{ (value | int) // 1048576 }}"
  unit_of_measurement: mBytes

- platform: snmp
  name: if_counter_eth0_out
  host: 192.168.1.1
  community: home
  scan_interval: 60
  baseoid: 1.3.6.1.2.1.2.2.1.16.4
  value_template: "{{ (value | int) // 1048576 }}"
  unit_of_measurement: mBytes

# COMMAND LINE SENSORS #########################################################

# Percentage of used space remaining on /dev/root
- platform: command_line
  name: Pi used space
  unit_of_measurement: "%"
  scan_interval: 10800
  command: "df | grep root | awk '{print $(NF-1)}' | sed 's/%//'"

- platform: command_line
  name: pi_cpu_load_1
  unit_of_measurement: "load"
  scan_interval: 60
  command: "cat /proc/loadavg | awk '{print $1}'"
  value_template: "{{ (value | float) }}"

- platform: command_line
  name: pi_cpu_load_5
  unit_of_measurement: "load"
  scan_interval: 60
  command: "cat /proc/loadavg | awk '{print $2}'"
  value_template: "{{ (value | float) }}"

- platform: command_line
  name: pi_cpu_load_15
  unit_of_measurement: "load"
  scan_interval: 60
  command: "cat /proc/loadavg | awk '{print $3}'"
  value_template: "{{ (value | float) }}"

- platform: command_line
  name: pi_cpu_temp
  unit_of_measurement: "째C (CPU)"
  scan_interval: 15
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  value_template: "{{ ((value | float) / 1000) | round(1) }}"

- platform: command_line
  name: git_latest_commit
  scan_interval: 300
  command: "bash /home/homeassistant/.homeassistant/scripts/git_local_commit_sensor.sh"

- platform: command_line
  name: git_latest_commit_origin
  scan_interval: 300
  command: "git --git-dir /home/homeassistant/.homeassistant/.git rev-parse origin/master | cut -c 1-7"


# MQTT Sensors here! ###########################################################

- platform: mqtt
  state_topic: zanzito/dphone/device_info
  name: dphone_battery_level
  value_template: "{{ value_json.battery_level }}"
  unit_of_measurement: "% charge"

- platform: mqtt
  state_topic: zanzito/dphone/device_info
  name: dphone_charge_type
  value_template: "{{ value_json.charge_type }}"

- platform: mqtt
  state_topic: zanzito/dphone/device_info
  name: dphone_current_wifi
  value_template: "{{ value_json.current_wifi }}"

- platform: mqtt
  state_topic: "stat/sonoff/STATUS5"
  name: s1_hostname
  value_template: "{{ value_json.StatusNET.Hostname }}"

- platform: mqtt
  state_topic: "stat/sonoff/STATUS5"
  name: s1_ipaddress
  value_template: "{{ value_json.StatusNET.IPAddress }}"

- platform: mqtt
  state_topic: "stat/sonoff/STATUS5"
  name: s1_dns
  value_template: "{{ value_json.StatusNET.DNSServer }}"

- platform: mqtt
  state_topic: "tele/sonoff/STATE"
  name: s1_vcc_voltage
  value_template: "{{ value_json.Vcc }}"
  unit_of_measurement: "V"

- platform: mqtt
  state_topic: "tele/sonoff/STATE"
  name: s1_rssi
  value_template: "{{ value_json.Wifi.RSSI }}"
  unit_of_measurement: "dB"

- platform: mqtt
  state_topic: "tele/sonoff/STATE"
  name: s1_uptime
  value_template: "{{ value_json.Uptime }}"
  unit_of_measurement: "Hours"

- platform: mqtt
  state_topic: "tele/sonoff/INFO3"
  name: s1_restart_reason
  value_template: "{{ value_json.RestartReason }}"

- platform: mqtt
  state_topic: "stat/xmas/STATUS5"
  name: s2_hostname
  value_template: "{{ value_json.StatusNET.Hostname }}"

- platform: mqtt
  state_topic: "stat/xmas/STATUS5"
  name: s2_ipaddress
  value_template: "{{ value_json.StatusNET.IPAddress }}"

- platform: mqtt
  state_topic: "stat/xmas/STATUS5"
  name: s2_dns
  value_template: "{{ value_json.StatusNET.DNSServer }}"

- platform: mqtt
  state_topic: "tele/xmas/STATE"
  name: s2_vcc_voltage
  value_template: "{{ value_json.Vcc }}"
  unit_of_measurement: "V"

- platform: mqtt
  state_topic: "tele/xmas/STATE"
  name: s2_rssi
  value_template: "{{ value_json.Wifi.RSSI }}"
  unit_of_measurement: "dB"

- platform: mqtt
  state_topic: "tele/xmas/STATE"
  name: s2_uptime
  value_template: "{{ value_json.Uptime }}"
  unit_of_measurement: "Hours"

- platform: mqtt
  state_topic: "tele/xmas/INFO3"
  name: s2_restart_reason
  value_template: "{{ value_json.RestartReason }}"

- platform: mqtt
  state_topic: "tele/xmas/INFO3"
  name: s2_restart_reason
  value_template: "{{ value_json.RestartReason }}"

- platform: mqtt
  state_topic: "omgateways/OMG1/DHTtoMQTT/dht1"
  name: OMG1_temp
  unit_of_measurement: "째C"
  value_template: "{{ value_json.temp }}"

- platform: mqtt
  state_topic: "omgateways/OMG2/DHTtoMQTT/dht1"
  name: OMG2_temp
  unit_of_measurement: "째C"
  value_template: "{{ value_json.temp }}"

- platform: mqtt
  state_topic: "omgateways/OMG3/DHTtoMQTT/dht1"
  name: OMG3_temp
  unit_of_measurement: "째C"
  value_template: "{{ value_json.temp }}"

- platform: mqtt
  state_topic: "omgateways/OMG1/DHTtoMQTT/dht1"
  name: OMG1_hum
  unit_of_measurement: "%"
  value_template: "{{ value_json.hum }}"

- platform: mqtt
  state_topic: "omgateways/OMG2/DHTtoMQTT/dht1"
  name: OMG2_hum
  unit_of_measurement: "%"
  value_template: "{{ value_json.hum }}"

- platform: mqtt
  state_topic: "omgateways/OMG3/DHTtoMQTT/dht1"
  name: OMG3_hum
  unit_of_measurement: "%"
  value_template: "{{ value_json.hum }}"

